// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig } from "prisma/config";

// Load .env.local natively for Vercel CLI pulled env vars
dotenv.config({ path: '.env.local' });

const databaseUrl = process.env["POSTGRES_PRISMA_URL"] ?? process.env["DATABASE_URL"] ?? process.env["POSTGRES_URL_NON_POOLING"];

if (!databaseUrl) {
  throw new Error("POSTGRES_PRISMA_URL ou DATABASE_URL não definida. Migração/Conexão pode falhar.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
